services:
  surau-gemilang-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: 192.168.0.137:5000/surau-gemilang-service:1.0.0
    container_name: surau-gemilang-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Jakarta
      - DB_HOST=surau-gemilang-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=surau_gemilang
    volumes:
      - surau_gemilang_app_data:/app/data
      - ./logs:/app/logs
    depends_on:
      surau-gemilang-mysql:
        condition: service_healthy
    networks:
      - microservice_net

  surau-gemilang-mysql:
    image: mysql:8.0
    container_name: surau-gemilang-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=surau_gemilang
    volumes:
      - surau_gemilang_mysql_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - microservice_net

  surau-gemilang-frontend:
    build:
      context: ./surau-gemilang-web
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    image: surau-gemilang-frontend:latest
    container_name: surau-gemilang-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - surau-gemilang-service
    networks:
      - microservice_net

volumes:
  surau_gemilang_mysql_data:
    external: true
  surau_gemilang_app_data:
    external: true

networks:
  microservice_net:
    external: true

